server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: azure
    password: azure1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #create: 매번 테이블 생성, update: 테이블 update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy #camel case기법으로 네이밍, PhysicalNamingStrategyStandardImpl: 변수명 그대로 네이밍
      use-new-id-generator-mappings: false #JPA의 넘버링 전략을 따라가지 않겠다는 의미.
    show-sql: true #sql 확인
    properties:
      hibernate.format_sql: true #sql prettier

  jackson:
    serialization:
      fail-on-empty-beans: false